// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoxvdVNCunZW7LCe-_GBcmToNbWnSXZk',
    appId: '1:800398940290:web:7e5c7c9bb5feac8d323c9b',
    messagingSenderId: '800398940290',
    projectId: 'wego-talk',
    authDomain: 'wego-talk.firebaseapp.com',
    storageBucket: 'wego-talk.firebasestorage.app',
    measurementId: 'G-X8SR4PTSK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkJmCmx04ceSj_rPYFoDIKQkwN6KEoT8',
    appId: '1:800398940290:android:995b186ddb3738c6323c9b',
    messagingSenderId: '800398940290',
    projectId: 'wego-talk',
    storageBucket: 'wego-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMTH8njq90-qYYoKApXvjDBYFjJSZN4A',
    appId: '1:800398940290:ios:dd1d9b30e5f98118323c9b',
    messagingSenderId: '800398940290',
    projectId: 'wego-talk',
    storageBucket: 'wego-talk.firebasestorage.app',
    iosClientId: '800398940290-e51m6v7j0mlr7enihr5p3pnj5brg0ill.apps.googleusercontent.com',
    iosBundleId: 'com.example.wegoMarriage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdMTH8njq90-qYYoKApXvjDBYFjJSZN4A',
    appId: '1:800398940290:ios:dd1d9b30e5f98118323c9b',
    messagingSenderId: '800398940290',
    projectId: 'wego-talk',
    storageBucket: 'wego-talk.firebasestorage.app',
    iosClientId: '800398940290-e51m6v7j0mlr7enihr5p3pnj5brg0ill.apps.googleusercontent.com',
    iosBundleId: 'com.example.wegoMarriage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdoxvdVNCunZW7LCe-_GBcmToNbWnSXZk',
    appId: '1:800398940290:web:18b58565905d48e7323c9b',
    messagingSenderId: '800398940290',
    projectId: 'wego-talk',
    authDomain: 'wego-talk.firebaseapp.com',
    storageBucket: 'wego-talk.firebasestorage.app',
    measurementId: 'G-HJ56QXSPVN',
  );
}
